package med.unittest.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.BaseIntentionProvider;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_AssertEquals_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_AssertEquals_InferenceRule() {
  }

  public void applyRule(final SNode equals, final TypeCheckingContext typeCheckingContext) {
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(equals, "expected", true);
      BaseIntentionProvider intentionProvider = null;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0c333457-e43b-4bb7-b0f8-d83406dad1d0(med.unittest.typesystem)", "5174648333271380347", 0, intentionProvider);
      _info_12389875345.setInequationGroup("");
      typeCheckingContext.createLessThanInequationStrong((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0c333457-e43b-4bb7-b0f8-d83406dad1d0(med.unittest.typesystem)", "5174648333271380338", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(equals, "actual", true), "r:0c333457-e43b-4bb7-b0f8-d83406dad1d0(med.unittest.typesystem)", "5174648333271380352", true), false, _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "med.unittest.structure.AssertEquals";
  }

  public boolean isApplicable(SNode argument) {
    return SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
  }

  public boolean overrides() {
    return false;
  }
}
