package med.features.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class AtomicFE_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isTrue_8261019787198922983(SNode thisNode) {
    return FeatureDeclaration_Behavior.call_isSelected_7715189151798165434(SLinkOperations.getTarget(thisNode, "feature", false));
  }

  public static boolean virtual_isTrue_1833385247967456436(SNode thisNode, List<SNode> selectionScenario) {
    return ListSequence.fromList(selectionScenario).contains(SLinkOperations.getTarget(thisNode, "feature", false));
  }
}
