package Templates.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Templates_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("6c17caf6-cfa9-4747-8eb3-4ebdfbfb51e4(Templates)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
