package med.components.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.intentions.BaseIntentionProvider;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_InterfaceProcedureImplementation_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_InterfaceProcedureImplementation_InferenceRule() {
  }

  public void applyRule(final SNode implementation, final TypeCheckingContext typeCheckingContext) {
    {
      SNode _nodeToCheck_1029348928467 = implementation;
      BaseIntentionProvider intentionProvider = null;
      typeCheckingContext.createEquation((SNode)typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:a33671bf-8144-43f9-bd6e-c5adb345b856(med.components.typesystem)", "7678656588249394751", true), (SNode)typeCheckingContext.typeOf(SLinkOperations.getTarget(implementation, "procedure", false), "r:a33671bf-8144-43f9-bd6e-c5adb345b856(med.components.typesystem)", "7678656588249412770", true), _nodeToCheck_1029348928467, null, "r:a33671bf-8144-43f9-bd6e-c5adb345b856(med.components.typesystem)", "7678656588249412765", intentionProvider);
    }
  }

  public String getApplicableConceptFQName() {
    return "med.components.structure.InterfaceProcedureImplementation";
  }

  public boolean isApplicable(SNode argument) {
    return SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
  }

  public boolean overrides() {
    return false;
  }
}
