package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CustomInclude extends MedBase {
  public static final String concept = "med.core.structure.CustomInclude";
  public static final String FILENAME = "filename";
  public static final String NEEDED_IN_HEADER = "neededInHeader";

  public CustomInclude(SNode node) {
    super(node);
  }

  public String getFilename() {
    return this.getProperty(CustomInclude.FILENAME);
  }

  public void setFilename(String value) {
    this.setProperty(CustomInclude.FILENAME, value);
  }

  public boolean getNeededInHeader() {
    return this.getBooleanProperty(CustomInclude.NEEDED_IN_HEADER);
  }

  public void setNeededInHeader(boolean value) {
    this.setBooleanProperty(CustomInclude.NEEDED_IN_HEADER, value);
  }

  public static CustomInclude newInstance(SModel sm, boolean init) {
    return (CustomInclude)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.CustomInclude", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CustomInclude newInstance(SModel sm) {
    return CustomInclude.newInstance(sm, false);
  }
}
