package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PlusMinusPrioExpression extends BinaryArithmeticExpression {
  public static final String concept = "med.core.structure.PlusMinusPrioExpression";

  public PlusMinusPrioExpression(SNode node) {
    super(node);
  }

  public static PlusMinusPrioExpression newInstance(SModel sm, boolean init) {
    return (PlusMinusPrioExpression)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.PlusMinusPrioExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PlusMinusPrioExpression newInstance(SModel sm) {
    return PlusMinusPrioExpression.newInstance(sm, false);
  }
}
