package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConstantExpression extends Expression implements ISimpleExpression {
  public static final String concept = "med.core.structure.ConstantExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public ConstantExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(ConstantExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ConstantExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ConstantExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ConstantExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ConstantExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ConstantExpression.VIRTUAL_PACKAGE, value);
  }

  public static ConstantExpression newInstance(SModel sm, boolean init) {
    return (ConstantExpression) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.ConstantExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConstantExpression newInstance(SModel sm) {
    return ConstantExpression.newInstance(sm, false);
  }
}
