package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DoWhileStatement extends Statement {
  public static final String concept = "med.core.structure.DoWhileStatement";
  public static final String CONDITION = "condition";
  public static final String BODY = "body";

  public DoWhileStatement(SNode node) {
    super(node);
  }

  public Expression getCondition() {
    return (Expression) this.getChild(Expression.class, DoWhileStatement.CONDITION);
  }

  public void setCondition(Expression node) {
    super.setChild(DoWhileStatement.CONDITION, node);
  }

  public StatementList getBody() {
    return (StatementList) this.getChild(StatementList.class, DoWhileStatement.BODY);
  }

  public void setBody(StatementList node) {
    super.setChild(DoWhileStatement.BODY, node);
  }

  public static DoWhileStatement newInstance(SModel sm, boolean init) {
    return (DoWhileStatement) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.DoWhileStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DoWhileStatement newInstance(SModel sm) {
    return DoWhileStatement.newInstance(sm, false);
  }
}
