package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class GenericStringType extends Type {
  public static final String concept = "med.core.structure.GenericStringType";

  public GenericStringType(SNode node) {
    super(node);
  }

  public static GenericStringType newInstance(SModel sm, boolean init) {
    return (GenericStringType) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.GenericStringType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static GenericStringType newInstance(SModel sm) {
    return GenericStringType.newInstance(sm, false);
  }
}
