package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ModuleImport extends MedBase {
  public static final String concept = "med.core.structure.ModuleImport";
  public static final String IMPORTED_MODULE = "importedModule";

  public ModuleImport(SNode node) {
    super(node);
  }

  public Module getImportedModule() {
    return (Module)this.getReferent(Module.class, ModuleImport.IMPORTED_MODULE);
  }

  public void setImportedModule(Module node) {
    super.setReferent(ModuleImport.IMPORTED_MODULE, node);
  }

  public static ModuleImport newInstance(SModel sm, boolean init) {
    return (ModuleImport)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.ModuleImport", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ModuleImport newInstance(SModel sm) {
    return ModuleImport.newInstance(sm, false);
  }
}
