package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleIntConstant extends SimpleConstant {
  public static final String concept = "med.core.structure.SimpleIntConstant";
  public static final String VALUE = "value";

  public SimpleIntConstant(SNode node) {
    super(node);
  }

  public int getValue() {
    return this.getIntegerProperty(SimpleIntConstant.VALUE);
  }

  public void setValue(int value) {
    this.setIntegerProperty(SimpleIntConstant.VALUE, value);
  }

  public static SimpleIntConstant newInstance(SModel sm, boolean init) {
    return (SimpleIntConstant)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.SimpleIntConstant", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleIntConstant newInstance(SModel sm) {
    return SimpleIntConstant.newInstance(sm, false);
  }
}
