package med.quantities.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.SubtypingRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.ISubtypingRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class superTypeOf_QuantityType_SubtypingRule extends SubtypingRule_Runtime implements ISubtypingRule_Runtime {
  public superTypeOf_QuantityType_SubtypingRule() {
  }

  public SNode getSubOrSuperType(SNode quantityType, TypeCheckingContext typeCheckingContext) {
    return SConceptOperations.createNewNode("med.quantities.structure.GenericQuantityType", null);
  }

  public String getApplicableConceptFQName() {
    return "med.quantities.structure.QuantityType";
  }

  public boolean isApplicable(SNode argument) {
    return SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
  }

  public boolean isWeak() {
    return false;
  }
}
