package med.components.structure;

/*Generated by MPS */

import med.core.structure.Type;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfaceType extends Type {
  public static final String concept = "med.components.structure.InterfaceType";
  public static final String INTERFACE = "interface";

  public InterfaceType(SNode node) {
    super(node);
  }

  public Interface getInterface() {
    return (Interface)this.getReferent(Interface.class, InterfaceType.INTERFACE);
  }

  public void setInterface(Interface node) {
    super.setReferent(InterfaceType.INTERFACE, node);
  }

  public static InterfaceType newInstance(SModel sm, boolean init) {
    return (InterfaceType)SModelUtil_new.instantiateConceptDeclaration("med.components.structure.InterfaceType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfaceType newInstance(SModel sm) {
    return InterfaceType.newInstance(sm, false);
  }
}
