package med.components.structure;

/*Generated by MPS */

import med.core.structure.Type;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PortAdapterType extends Type {
  public static final String concept = "med.components.structure.PortAdapterType";
  public static final String ADAPTER = "adapter";

  public PortAdapterType(SNode node) {
    super(node);
  }

  public PortAdaptor getAdapter() {
    return (PortAdaptor)this.getReferent(PortAdaptor.class, PortAdapterType.ADAPTER);
  }

  public void setAdapter(PortAdaptor node) {
    super.setReferent(PortAdapterType.ADAPTER, node);
  }

  public static PortAdapterType newInstance(SModel sm, boolean init) {
    return (PortAdapterType)SModelUtil_new.instantiateConceptDeclaration("med.components.structure.PortAdapterType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PortAdapterType newInstance(SModel sm) {
    return PortAdapterType.newInstance(sm, false);
  }
}
