package med.components.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RequiredPort extends ProceduralPort {
  public static final String concept = "med.components.structure.RequiredPort";

  public RequiredPort(SNode node) {
    super(node);
  }

  public static RequiredPort newInstance(SModel sm, boolean init) {
    return (RequiredPort)SModelUtil_new.instantiateConceptDeclaration("med.components.structure.RequiredPort", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RequiredPort newInstance(SModel sm) {
    return RequiredPort.newInstance(sm, false);
  }
}
