echo Executing NeXTTool to upload ../../../ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /cygdrive/C/ide/Cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=../../../ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
