package SQLInJava.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class SQLStatementStatement_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "select", "tomSQL.structure.SelectStatement");
  }
}
