package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface IHasIdentifierName extends INamedConcept {
  public static final String concept = "med.core.structure.IHasIdentifierName";
}
