package med.core.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ExternalModule_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<SNode> virtual_exportedElements_7301321101283467875(SNode thisNode) {
    List<SNode> result = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(result).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "procedures", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "export");
      }
    }));
    ListSequence.fromList(result).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "structs", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "export");
      }
    }));
    ListSequence.fromList(result).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "enums", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "export");
      }
    }));
    ListSequence.fromList(result).addSequence(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "typedefs", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getBoolean(it, "export");
      }
    }));
    return result;
  }

  public static boolean call_representsExternalHeaderFile_7647825645222690352(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "existingHeaderFile") != null;
  }

  public static boolean virtual_hasToBeGenerated_7647825645222142673(SNode thisNode) {
    return !(ExternalModule_Behavior.call_representsExternalHeaderFile_7647825645222690352(thisNode));
  }
}
