package med.core.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.SubtypingRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.ISubtypingRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class supertypeOf_ArrayType_Pointer_SubtypingRule extends SubtypingRule_Runtime implements ISubtypingRule_Runtime {
  public supertypeOf_ArrayType_Pointer_SubtypingRule() {
  }

  public SNode getSubOrSuperType(SNode arrayType, TypeCheckingContext typeCheckingContext) {
    SNode ptr = SConceptOperations.createNewNode("med.core.structure.PointerType", null);
    SLinkOperations.setTarget(ptr, "baseType", SNodeOperations.copyNode(SLinkOperations.getTarget(arrayType, "elementType", true)), true);
    return ptr;
  }

  public String getApplicableConceptFQName() {
    return "med.core.structure.ArrayType";
  }

  public boolean isApplicable(SNode argument) {
    return SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
  }

  public boolean isWeak() {
    return false;
  }
}
