package med.bitdata.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_7680622939171046606(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "lvalue", true), "med.bitdata.structure.BitAccessExpression");
  }

  public static boolean baseMappingRule_Condition_7680622939171433441(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return (SNodeOperations.getAncestor(_context.getNode(), "med.core.structure.AssignmentStatement", false, false) == null);
  }

  public static Object propertyMacro_GetPropertyValue_7680622939171317851(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lvalue", true), "med.bitdata.structure.BitAccessExpression"), "bits", false), "from");
  }

  public static Object propertyMacro_GetPropertyValue_7680622939171317863(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lvalue", true), "med.bitdata.structure.BitAccessExpression"), "bits", false), "to");
  }

  public static Object propertyMacro_GetPropertyValue_7680622939171433501(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "bits", false), "from");
  }

  public static Object propertyMacro_GetPropertyValue_7680622939171433516(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "bits", false), "to");
  }

  public static SNode sourceNodeQuery_7680622939171202362(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lvalue", true), "med.bitdata.structure.BitAccessExpression"), "expression", true);
  }

  public static SNode sourceNodeQuery_7680622939171162182(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "rvalue", true);
  }

  public static SNode sourceNodeQuery_7680622939171433490(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }
}
