package med.statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Transition_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "guard", "med.core.structure.TrueLiteral");
  }
}
