package med.components.structure;

/*Generated by MPS */

import med.core.structure.MedBase;
import med.core.structure.IExportableModuleContent;
import med.core.structure.IHasIdentifierName;
import med.core.structure.IDocumentable;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Component extends MedBase implements IExportableModuleContent, IHasIdentifierName, IDocumentable {
  public static final String concept = "med.components.structure.Component";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAME = "name";
  public static final String TEXT = "text";
  public static final String EXPORT = "export";
  public static final String PORTS = "ports";

  public Component(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Component.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Component.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Component.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Component.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Component.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Component.VIRTUAL_PACKAGE, value);
  }

  public String getName() {
    return this.getProperty(Component.NAME);
  }

  public void setName(String value) {
    this.setProperty(Component.NAME, value);
  }

  public String getText() {
    return this.getProperty(Component.TEXT);
  }

  public void setText(String value) {
    this.setProperty(Component.TEXT, value);
  }

  public boolean getExport() {
    return this.getBooleanProperty(Component.EXPORT);
  }

  public void setExport(boolean value) {
    this.setBooleanProperty(Component.EXPORT, value);
  }

  public int getPortsesCount() {
    return this.getChildCount(Component.PORTS);
  }

  public Iterator<Port> portses() {
    return this.children(Port.class, Component.PORTS);
  }

  public List<Port> getPortses() {
    return this.getChildren(Port.class, Component.PORTS);
  }

  public void addPorts(Port node) {
    this.addChild(Component.PORTS, node);
  }

  public void insertPorts(Port prev, Port node) {
    this.insertChild(prev, Component.PORTS, node);
  }

  public static Component newInstance(SModel sm, boolean init) {
    return (Component)SModelUtil_new.instantiateConceptDeclaration("med.components.structure.Component", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Component newInstance(SModel sm) {
    return Component.newInstance(sm, false);
  }
}
