package med.components.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IRequired extends INodeAdapter {
  public static final String concept = "med.components.structure.IRequired";
}
