package med.components.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RequiredPort extends ProceduralPort implements IRequired {
  public static final String concept = "med.components.structure.RequiredPort";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public RequiredPort(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(RequiredPort.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(RequiredPort.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(RequiredPort.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(RequiredPort.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(RequiredPort.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(RequiredPort.VIRTUAL_PACKAGE, value);
  }

  public static RequiredPort newInstance(SModel sm, boolean init) {
    return (RequiredPort)SModelUtil_new.instantiateConceptDeclaration("med.components.structure.RequiredPort", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RequiredPort newInstance(SModel sm) {
    return RequiredPort.newInstance(sm, false);
  }
}
