package med.features.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FeatureDeclaration extends BaseConcept implements INamedConcept, IFEValidIdentifier {
  public static final String concept = "med.features.structure.FeatureDeclaration";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public FeatureDeclaration(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(FeatureDeclaration.NAME);
  }

  public void setName(String value) {
    this.setProperty(FeatureDeclaration.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(FeatureDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(FeatureDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(FeatureDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(FeatureDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(FeatureDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(FeatureDeclaration.VIRTUAL_PACKAGE, value);
  }

  public static FeatureDeclaration newInstance(SModel sm, boolean init) {
    return (FeatureDeclaration)SModelUtil_new.instantiateConceptDeclaration("med.features.structure.FeatureDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FeatureDeclaration newInstance(SModel sm) {
    return FeatureDeclaration.newInstance(sm, false);
  }
}
