package med.features.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class VariantDisplayMode extends DisplayMode {
  public static final String concept = "med.features.structure.VariantDisplayMode";

  public VariantDisplayMode(SNode node) {
    super(node);
  }

  public static VariantDisplayMode newInstance(SModel sm, boolean init) {
    return (VariantDisplayMode)SModelUtil_new.instantiateConceptDeclaration("med.features.structure.VariantDisplayMode", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static VariantDisplayMode newInstance(SModel sm) {
    return VariantDisplayMode.newInstance(sm, false);
  }
}
