# Target specific macros
TARGET = linefollower_OSEK
TARGET_SOURCES = \
	linefollower.c
TOPPERS_OSEK_OIL_SOURCE = ./linefollower.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
