package util.editor.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.List;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ITableNature_Behavior {
  private static Class[] PARAMETERS_7400233627845195012 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static List<SNode> call_rowHeaders_7400233627845195012(SNode thisNode) {
    return (List<SNode>) BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(thisNode, "util.editor.structure.ITableNature"), "virtual_rowHeaders_7400233627845195012", PARAMETERS_7400233627845195012);
  }

  public static List<SNode> callSuper_rowHeaders_7400233627845195012(SNode thisNode, String callerConceptFqName) {
    return (List<SNode>) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "util.editor.structure.ITableNature"), callerConceptFqName, "virtual_rowHeaders_7400233627845195012", PARAMETERS_7400233627845195012);
  }
}
