package ds.twowheel.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class addBump_Intention extends BaseIntention implements Intention {
  public addBump_Intention() {
  }

  public String getConcept() {
    return "ds.twowheel.structure.BlockStatement";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "twowheel: add bump reaction";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SLinkOperations.setNewChild(node, "bumpReaction", "ds.twowheel.structure.RSStatement");
    editorContext.select(SLinkOperations.getTarget(node, "bumpReaction", true));
  }

  public String getLocationString() {
    return "ds.twowheel.intentions";
  }
}
