package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EnumType extends Type {
  public static final String concept = "med.core.structure.EnumType";
  public static final String ENUM = "enum";

  public EnumType(SNode node) {
    super(node);
  }

  public EnumDeclaration getEnum() {
    return (EnumDeclaration) this.getReferent(EnumDeclaration.class, EnumType.ENUM);
  }

  public void setEnum(EnumDeclaration node) {
    super.setReferent(EnumType.ENUM, node);
  }

  public static EnumType newInstance(SModel sm, boolean init) {
    return (EnumType) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.EnumType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EnumType newInstance(SModel sm) {
    return EnumType.newInstance(sm, false);
  }
}
