package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Int64 extends Type implements IStdInt {
  public static final String concept = "med.core.structure.Int64";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public Int64(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Int64.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Int64.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Int64.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Int64.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Int64.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Int64.VIRTUAL_PACKAGE, value);
  }

  public static Int64 newInstance(SModel sm, boolean init) {
    return (Int64) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.Int64", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Int64 newInstance(SModel sm) {
    return Int64.newInstance(sm, false);
  }
}
