package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NoopStatement extends Statement {
  public static final String concept = "med.core.structure.NoopStatement";

  public NoopStatement(SNode node) {
    super(node);
  }

  public static NoopStatement newInstance(SModel sm, boolean init) {
    return (NoopStatement)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.NoopStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NoopStatement newInstance(SModel sm) {
    return NoopStatement.newInstance(sm, false);
  }
}
