package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Type extends MedBase {
  public static final String concept = "med.core.structure.Type";

  public Type(SNode node) {
    super(node);
  }

  public static Type newInstance(SModel sm, boolean init) {
    return (Type) SModelUtil_new.instantiateConceptDeclaration("med.core.structure.Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Type newInstance(SModel sm) {
    return Type.newInstance(sm, false);
  }
}
