package featureDependencies.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class FeatureClause_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "isNew", "" + true);
  }

  public static boolean call_isTrue_8261019787198925259(SNode thisNode, boolean forUI) {
    if (SPropertyOperations.getBoolean(thisNode, "isNew") && forUI) {
      return true;
    }
    if (SLinkOperations.getTarget(thisNode, "expression", true) == null) {
      return true;
    }
    return BaseFE_Behavior.call_isTrue_8261019787198922983(SLinkOperations.getTarget(thisNode, "expression", true));
  }
}
