package featureDependencies.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class NotFE_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isTrue_8261019787198922983(SNode thisNode) {
    return !(BaseFE_Behavior.call_isTrue_8261019787198922983(SLinkOperations.getTarget(thisNode, "expr", true)));
  }
}
