package featureDependencies.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class SimpleFeatureDeclaration_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isSelected_7715189151798165434(SNode thisNode) {
    return SPropertyOperations.getBoolean(thisNode, "selected");
  }
}
