package ds.twowheel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TurnLeftStatement extends ContinuousStatement {
  public static final String concept = "ds.twowheel.structure.TurnLeftStatement";

  public TurnLeftStatement(SNode node) {
    super(node);
  }

  public static TurnLeftStatement newInstance(SModel sm, boolean init) {
    return (TurnLeftStatement)SModelUtil_new.instantiateConceptDeclaration("ds.twowheel.structure.TurnLeftStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TurnLeftStatement newInstance(SModel sm) {
    return TurnLeftStatement.newInstance(sm, false);
  }
}
