package ds.twowheel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TurnAround extends ContinuousStatement {
  public static final String concept = "ds.twowheel.structure.TurnAround";
  public static final String LEFT = "left";

  public TurnAround(SNode node) {
    super(node);
  }

  public boolean getLeft() {
    return this.getBooleanProperty(TurnAround.LEFT);
  }

  public void setLeft(boolean value) {
    this.setBooleanProperty(TurnAround.LEFT, value);
  }

  public static TurnAround newInstance(SModel sm, boolean init) {
    return (TurnAround)SModelUtil_new.instantiateConceptDeclaration("ds.twowheel.structure.TurnAround", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TurnAround newInstance(SModel sm) {
    return TurnAround.newInstance(sm, false);
  }
}
