package med.features.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.AttributesRolesUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class addReplacementFeatureDependencyAnnotation_Intention extends BaseIntention implements Intention {
  public addReplacementFeatureDependencyAnnotation_Intention() {
  }

  public String getConcept() {
    return "jetbrains.mps.lang.core.structure.BaseConcept";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "features: add replacement";
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(this.isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  public boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return SLinkOperations.getTarget(node, AttributesRolesUtil.childRoleFromAttributeRole("featureDependencyAnnotation"), true) == null && !(SNodeOperations.isInstanceOf(node, "med.features.structure.ReplacementFeatureClause"));
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode clause = SConceptOperations.createNewNode("med.features.structure.ReplacementFeatureClause", null);
    SLinkOperations.setTarget(node, AttributesRolesUtil.childRoleFromAttributeRole("replacementFeatureDependencyAnnotation"), clause, true);
    editorContext.selectBefore(SLinkOperations.getTarget(clause, "expression", true));
  }

  public String getLocationString() {
    return "med.features.intentions";
  }
}
