package med.dataflowblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Split_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.addNewChild(thisNode, "outs", "med.dataflowblocks.structure.SplitOut");
    SLinkOperations.addNewChild(thisNode, "outs", "med.dataflowblocks.structure.SplitOut");
  }
}
