package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DivisionExpression extends MulDivPrioExpression {
  public static final String concept = "med.core.structure.DivisionExpression";

  public DivisionExpression(SNode node) {
    super(node);
  }

  public static DivisionExpression newInstance(SModel sm, boolean init) {
    return (DivisionExpression)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.DivisionExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DivisionExpression newInstance(SModel sm) {
    return DivisionExpression.newInstance(sm, false);
  }
}
