package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IContributesToHeader extends INodeAdapter {
  public static final String concept = "med.core.structure.IContributesToHeader";
}
