package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IDocumentable extends INodeAdapter {
  public static final String concept = "med.core.structure.IDocumentable";
  public static final String TEXT = "text";

  public String getText();
  public void setText(String value);
}
