package med.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StringType extends GenericStringType {
  public static final String concept = "med.core.structure.StringType";
  public static final String LENGTH = "length";

  public StringType(SNode node) {
    super(node);
  }

  public int getLength() {
    return this.getIntegerProperty(StringType.LENGTH);
  }

  public void setLength(int value) {
    this.setIntegerProperty(StringType.LENGTH, value);
  }

  public static StringType newInstance(SModel sm, boolean init) {
    return (StringType)SModelUtil_new.instantiateConceptDeclaration("med.core.structure.StringType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StringType newInstance(SModel sm) {
    return StringType.newInstance(sm, false);
  }
}
