package featureDependencies.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.MappingScriptContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import featureDependencies.behavior.FeatureClause_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class QueriesGenerated {
  public static void mappingScript_CodeBlock_8261019787197350454(final IOperationContext operationContext, final MappingScriptContext _context) {
    for (SNode cls : SModelOperations.getNodes(_context.getModel(), "featureDependencies.structure.FeatureClause")) {
      if (!(FeatureClause_Behavior.call_isTrue_8261019787198925259(cls, false))) {
        SNodeOperations.deleteNode(SNodeOperations.getParent(cls));
      }
      SNodeOperations.deleteNode(cls);
    }
  }
}
