package med.quantities.structure;

/*Generated by MPS */

import med.core.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MarkAsInternalOperator extends Expression {
  public static final String concept = "med.quantities.structure.MarkAsInternalOperator";
  public static final String VALUE = "value";

  public MarkAsInternalOperator(SNode node) {
    super(node);
  }

  public int getValue() {
    return this.getIntegerProperty(MarkAsInternalOperator.VALUE);
  }

  public void setValue(int value) {
    this.setIntegerProperty(MarkAsInternalOperator.VALUE, value);
  }

  public static MarkAsInternalOperator newInstance(SModel sm, boolean init) {
    return (MarkAsInternalOperator)SModelUtil_new.instantiateConceptDeclaration("med.quantities.structure.MarkAsInternalOperator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MarkAsInternalOperator newInstance(SModel sm) {
    return MarkAsInternalOperator.newInstance(sm, false);
  }
}
