package med.tasks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class SchedulingPolicy_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "priority", "" + 1);
  }
}
