package util.editor.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.ConceptFunction;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class QueryFunction_HeaderNodes extends ConceptFunction {
  public static final String concept = "util.editor.structure.QueryFunction_HeaderNodes";

  public QueryFunction_HeaderNodes(SNode node) {
    super(node);
  }

  public static QueryFunction_HeaderNodes newInstance(SModel sm, boolean init) {
    return (QueryFunction_HeaderNodes) SModelUtil_new.instantiateConceptDeclaration("util.editor.structure.QueryFunction_HeaderNodes", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static QueryFunction_HeaderNodes newInstance(SModel sm) {
    return QueryFunction_HeaderNodes.newInstance(sm, false);
  }
}
