package med.features.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TryAgain extends RetryStep {
  public static final String concept = "med.features.structure.TryAgain";

  public TryAgain(SNode node) {
    super(node);
  }

  public static TryAgain newInstance(SModel sm, boolean init) {
    return (TryAgain) SModelUtil_new.instantiateConceptDeclaration("med.features.structure.TryAgain", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TryAgain newInstance(SModel sm) {
    return TryAgain.newInstance(sm, false);
  }
}
