package med.features.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.ModelAccess;
import med.features.rt.ValidationBaseBuilder;

public class updateValidationBase_Intention extends BaseIntention {
  public updateValidationBase_Intention() {
  }

  public String getConcept() {
    return "med.features.structure.FeatureDependencyConfiguration";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "features: update validtion base";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    ModelAccess.instance().runWriteActionInCommand(new Runnable() {
      public void run() {
        ValidationBaseBuilder.buildValidFeatureList(node);
      }
    });
  }

  public String getLocationString() {
    return "med.features.intentions";
  }
}
