package med.components.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.constraints.CanBeAParentContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class InterfaceProcParameterReference_Constraints {
  public static boolean canBeAParent(final IOperationContext operationContext, final CanBeAParentContext _context) {
    return (SNodeOperations.getAncestor(_context.getNode(), "med.components.structure.InterfaceProcedureImplementation", true, false) != null);
  }
}
