package med.messagecomponents.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Messagecomponents_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("9e6c81d8-26e0-4cc9-98c1-b724ce51d7bf(med.messagecomponents)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
