package med.collections.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Collections_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("6e44d351-5a59-4b50-a737-fd0fc110e1d6(med.collections)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
